DROP TRIGGER Inc_enrollment_number
DROP TRIGGER Dec_enrollment_number

DROP PROCEDURE Get_TA;
DROP PROCEDURE GetStudentCourse;

DROP FUNCTION Course_Instructor

DROP VIEW Student_Grade_A;
DROP VIEW TA_COURSE;

DROP TABLE ENROLLED;
DROP TABLE NON_WEB_BASED_COURSE;
DROP TABLE WEB_BASED_COURSE;
DROP TABLE CLASS_ROOM;
DROP TABLE COURSE;
DROP TABLE TEACHING_ASSISTANT;
DROP TABLE STUDENT;
DROP TABLE INSTRUCTOR;
